DROP DATABASE IF EXISTS FACTBOOK;
CREATE DATABASE FACTBOOK;
USE FACTBOOK;

CREATE TABLE `CountryMain` (
    `Id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `CountryCode` CHAR(2) NOT NULL,
	`CountryName` VARCHAR(50) NOT NULL, 
	`Region` VARCHAR(30) NOT NULL, 
	`Introduction` TEXT
);

	
CREATE TABLE `city` (
    `Id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `CountryCode` CHAR(2) NOT NULL, 
	`CityName` VARCHAR(50) NOT NULL, 
	`Population` INT,
	`Capital` BOOLEAN
);

CREATE TABLE `border` (
    `Id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `CountryCode` CHAR(2) NOT NULL, 
	`BorderCountry` VARCHAR(50) NOT NULL, 
	`BorderLengthKM` DOUBLE
);


CREATE TABLE `geography` (
    `Id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `CountryCode` CHAR(2) NOT NULL,
    `Lat` DECIMAL( 8, 1 ),
    `Lng` DECIMAL( 8, 1 ),
	`LandArea` DECIMAL( 9, 1 ),
    `WaterArea` DECIMAL( 8, 1 ),
    `LandBoundaries` DECIMAL( 8, 1 ),
    `Coastline` DECIMAL( 8, 1 ),
	`MeanElevation` DECIMAL( 8, 1 ),
	`LowestPointDistance` DECIMAL( 8, 1 ),
	`LowestPointName` VARCHAR(70),
	`HighestPointDistance` DECIMAL( 8, 1 ),
	`HighestPointName` VARCHAR(60),
	`IrrigatedLand` DECIMAL( 8, 1 )
);

CREATE TABLE `society` (
    `Id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `CountryCode` CHAR(2),
    `Population` INT,
    `Male0_14` INT,
	`Female0_14` INT,
	`Male15_24` INT,
	`Female15_24` INT,
	`Male25_54` INT,
	`Female25_54` INT,
	`Male55_64` INT,
	`Female55_64` INT,
	`Male65` INT,
	`Female65` INT,
    `YouthDependencyRatio` DECIMAL( 3, 1 ),
    `ElderlyDependencyRatio` DECIMAL( 3, 1 ),
    `PotentialSupportRatio` DECIMAL( 3, 1 ),
	`MedianAgeMale` DECIMAL( 3, 1 ),
	`MedianAgeFemale` DECIMAL( 3, 1 ),
	`PopulationGrowthRate` DECIMAL( 3, 2 ),
	`BirthRatePer1K` DECIMAL( 3, 1 ),
	`DeathRatePer1K` DECIMAL( 3, 1 ),
	`NetMigrationRate` DECIMAL( 3, 1 ),
	`UrbanPopulation` INT,
	`UrbanizationRate` DECIMAL( 3, 2 ),
	`MotherMeanAgeAtFirstBirth` DECIMAL( 3, 1 ),
	`MaternalMortalityRatePer100K` INT,
	`InfantMaleMortalityRatePer1K` DECIMAL( 4, 1 ),
	`InfantFemaleMortalityRatePer1K` DECIMAL( 4, 1 ),
	`MaleLifeExpectancy` DECIMAL( 3, 1 ),
	`FemaleLifeExpectancy` DECIMAL( 3, 1 ),
	`ChildrenBornPerWoman` DECIMAL( 3, 2 ),
	`ContraceptivePrevalencePCT` DECIMAL( 3, 1 ),
	`HealthExpenditurePCT` DECIMAL( 3, 1 ),
	`PhysiciansPer1K` DECIMAL( 3, 2 ),
	`HospitalBedPer1K` DECIMAL( 3, 1 ),
	`ImprovedUrbanDrinkingWaterPCT` DECIMAL( 4, 1 ),
	`ImprovedRuralDrinkingWaterPCT` DECIMAL( 4, 1 ),
	`ImprovedUrbanSanitationFacilityAccessPCT` DECIMAL( 3, 1 ),
	`ImprovedRuralSanitationFacilityAccessPCT` DECIMAL( 3, 1 ),
	`ImprovedTotalSanitationFacilityAccessPCT` DECIMAL( 3, 1 ),
	`HIVAIDSPrevalencePCT` DECIMAL( 3, 1 ),
	`HIVAIDSAfflicted` INT,
	`HIVAIDSDeaths` INT,
	`InfectiousDiseasesRisk` VARCHAR(15),
	`AdultObesityPCT` Decimal( 3, 1 ),
	`EducationExpenditures` DECIMAL( 3, 1 ),
	`MaleLiteracy` Decimal( 4, 1 ),
	`FemaleLiteracy` Decimal( 4, 1 ),
	`MaleSchoolLifeExpectancy` INT,
	`FemaleSchoolLifeExpectancy` INT,
	`MaleUnemployment` Decimal( 3, 1 ),
	`FemaleUnemployment` Decimal( 3, 1 )
);

CREATE TABLE `government` (
    `Id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `CountryCode` CHAR(2) NOT NULL,
	`GovernmentType` VARCHAR(255),
    `CapitalLat` DECIMAL( 8, 1 ),
    `CapitalLng` DECIMAL( 8, 1 ),
	`TimeDifference` VARCHAR(10),
	`DaylightSavingTime` VARCHAR(200),
	`IndependenceDate` TEXT,
	`NationalHoliday` TEXT,
	`LegalSystem` TEXT,
	`CitizenshipByBirth` BOOLEAN,
	`CitizenshipByDescent` VARCHAR(255),
	`DualCitizenship` BOOLEAN,
	`Naturalization` VARCHAR(150),
	`SuffrageAge` VARCHAR(150),
	`SuffrageCompulsory` BOOLEAN,
	`ChiefOfState` VARCHAR(100),
	`HeadOfGovernment` VARCHAR(100),
	`DiplomatToUS` VARCHAR(100),
	`DiplomatFromUS` VARCHAR(100)
);

CREATE TABLE `economy` (
    `Id` INT NOT NULL AUTOINCREMENT PRIMARY KEY,
    `CountryCode` CHAR(2) NOT NULL,
    `Overview` TEXT,
	`GDPPurchasingPowerParity` BIGINT,
	`GDPOfficialExchangeRate` BIGINT,
	`GDPRealGrowthRate` Decimal( 4, 1 ),
	`GDPPerCapita` INT,
	`GrossNationalSaving` Decimal( 3, 1 ),
	`HouseholdConsumption` Decimal( 4, 1 ),
	`GovernmentConsumption` Decimal( 3, 1 ),
	`InvestmentFixedCapital` Decimal( 3, 1 ),
	`InvestmentInventories` Decimal( 3, 1 ),
	`Exports` Decimal( 4, 1 ),
	`Imports` Decimal( 4, 1 ),
	`GDPAgriculture` Decimal( 3, 1 ),
	`GDPIndustry` Decimal( 3, 1 ),
	`GDPServices` Decimal( 3, 1 ),
	`AgricultureProducts` TEXT,
	`Industries` TEXT,
	`IndustrialGrowth` Decimal( 3, 1 ),
	`LaborForce` INT,
	`OccupationAgriculture` Decimal( 3, 1 ),
	`OccupationIndustry` Decimal( 3, 1 ),
	`OccupationServices` Decimal( 3, 1 ),
	`UnemploymentRate` Decimal( 3, 1 ),
	`BelowPovertyLine` Decimal( 3, 1 ),
	`Lowest10PCTConsumption` Decimal( 3, 1 ),
	`Highest10PCTConsumption` Decimal( 3, 1 ),
	`GiniIndexIncome` Decimal( 3, 1 ),
	`Revenues` BIGINT,
	`Expenditures` BIGINT,
	`Taxes` Decimal( 3, 1 ),
	`BudgetSurplus` Decimal( 4, 1 ),
	`PublicDebt` Decimal( 4, 1 ),
	`FiscalYear` VARCHAR(30),
	`Inflation` Decimal( 3, 1 ),
	`CentralBankDiscount` Decimal( 4, 2 ),
	`CommercialBankLending` Decimal( 4, 2 ), 
	`NarrowMoney` BIGINT,
	`BroadMoney` BIGINT,
	`DomesticCredit` BIGINT,
	`ValueTradedShares` BIGINT,
	`CurrentAccountBalance` BIGINT,
	`ExportsTotal` BIGINT,
	`ExportsCommodities` BIGINT,
	`ExportsPartners` VARCHAR(200),
	`ImportsTotal` BIGINT,
	`ImportsCommodities` VARCHAR(200),
	`ImportsPartners` BIGINT,
	`ForeignGoldReserves` BIGINT,
	`DebtExternal` BIGINT,
	`ForeignInvestmentHome` BIGINT,
	`ForeignInvestmentAbroad` BIGINT,
	`CurrencyText` VARCHAR(80),
	`ExchangeRate` Decimal( 13, 5 )
)


